version: 3.0.1

services:
  mysql-container:
    image: mysql:8.0.26
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car
      MYSQL_PASSWORD=: root
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
  redis:
    image: redis:bullseye
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  mockserver:
    image: mockserver/mockserver
    container_name: mockserver
    restart: always
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserver.json
    volumes:
      - ./mockserver:/config
